// Nombres oficiales basados en el documento de la ANAM (Agencia Nacional de Aduanas de México)
export const FILE_NAMES: Record<string, string> = {
  '501': '501 - Datos generales',
  '502': '502 - Transporte',
  '503': '503 - Guías',
  '504': '504 - Contenedores',
  '505': '505 - Facturas',
  '506': '506 - Fechas del pedimento',
  '507': '507 - Casos del pedimento',
  '508': '508 - Ctas aduaneras garantía',
  '509': '509 - Tasas del pedimento',
  '510': '510 - Contribuciones pedimento',
  '511': '511 - Observaciones pedimento',
  '512': '512 - Descargos de mercancías',
  '520': '520 - Destinatarios mercancía',
  '551': '551 - Partidas',
  '552': '552 - Mercancías',
  '553': '553 - Permisos de la partida',
  '554': '554 - Casos de la partida',
  '555': '555 - Ctas aduaneras (partida)',
  '556': '556 - Tasas contrib (partida)',
  '557': '557 - Contribuciones partida',
  '558': '558 - Observaciones partida',
  '701': '701 - Rectificaciones',
  '702': '702 - Diferencias contrib',
};

export const CRITICAL_FILES = ['501', '551'];

export const MONTH_NAMES = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
];

// Regex para validar formato de pedimento unificado: AA-AAA-AAAA-AAAAAAA
export const PEDIMENTO_REGEX = /^\d{2}-\d{3}-\d{4}-\d{7}$/;

// Archivos a nivel pedimento (relación por Patente + Índice + Sección)
export const PEDIMENTO_LEVEL_FILES = ['501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '520', '701', '702'];

// Archivos a nivel partida (relación por Patente + Índice + Sección + Fracción + Secuencia)
export const PARTIDA_LEVEL_FILES = ['551', '552', '553', '554', '555', '556', '557', '558'];

/**
 * Encabezados oficiales por archivo, basados en "Descripción de Campos" de la ANAM.
 * La primera columna "Pedimento" se agrega automáticamente por el enriquecimiento.
 * Los campos corresponden a las columnas del archivo .asc original (pipe-delimited).
 * Ref: https://www.anam.gob.mx/wp-content/uploads/2022/08/Descripcion-de-Campos-1.pdf
 */
export const COLUMN_HEADERS: Record<string, string[]> = {
  '501': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de recepción de pedimento',
    'Fecha de pago',
    'Tipo de cambio',
    'Fletes',
    'Seguros',
    'Embalajes',
    'Otros incrementales',
    'Otros deducibles',
    'Peso bruto de la mercancía',
    'Clave de medio de transporte de salida',
    'Descripción Clave de medio de transporte de salida',
    'Clave de medio de transporte de arribo',
    'Descripción Clave de medio de transporte de arribo',
    'Clave de medio de transporte de entrada o salida del país',
    'Descripción Clave de medio de transporte de entrada o salida del país',
    'Clave de destino de la mercancía',
    'Descripción destino de la mercancía',
    'Clave de sección aduanera de entrada',
    'CURP del agente o apoderado aduanal',
    'Nombre del contribuyente',
    'Dirección del contribuyente',
    'Transporte (Decrementables)',
    'Seguro (Decrementables)',
    'Carga (Decrementables)',
    'Descarga (Decrementables)',
    'Otros Decrementables',
  ],
  '502': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'RFC del transportista',
    'CURP del transportista',
    'Nombre del transportista',
    'Clave de país del transporte',
    'Identificador del transporte',
  ],
  '503': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Número de guía o manifiesto',
    'Clave de tipo de guía',
  ],
  '504': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Número del contenedor',
    'Clave de tipo de contenedor',
    'Descripción del contenedor',
  ],
  '505': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de recepción de pedimento',
    'Fecha de pago',
    'Número de la factura',
    'Fecha de facturación',
    'Clave de término de facturación',
    'Valor en dólares',
    'Clave de moneda de facturación',
    'Valor en moneda extranjera',
    'Clave de país de facturación',
    'Proveedor de la mercancía',
    'Identificación fiscal del proveedor',
    'Dirección',
  ],
  '506': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Tipo de fecha',
    'Fecha de operación',
    'Fecha de validación o de pago real',
  ],
  '507': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Identificador del caso',
    'Descripción del Identificador',
    'Complemento 1',
    'Complemento 2',
  ],
  '508': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Clave de institución emisora',
    'Número de cuenta',
    'Folio de la constancia',
    'Fecha de la constancia',
    'Clave de tipo de cuenta',
    'Clave de garantía',
    'Valor unitario del título',
    'Total de la garantía',
    'Cantidad en unidades de medida del precio estimado',
    'Títulos asignados',
  ],
  '509': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Clave de contribución',
    'Contribución',
    'Descripción de la contribución',
    'Tasa de la contribución',
    'Clave de tipo de la tasa',
    'Descripción de la tasa',
  ],
  '510': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Clave de contribución',
    'Descripción de la contribución',
    'Clave de forma de pago',
    'Descripción forma de pago',
    'Importe del pago',
  ],
  '511': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Secuencia de la observación',
    'Observaciones',
    'Fecha de validación o de pago real',
  ],
  '512': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Pedimento original',
    'Clave de pedimento original',
    'Fecha de la operación original',
    'Fracción arancelaria original',
    'Clave de unidad de medida original',
    'Unidad de medida original',
    'Cantidad de mercancía descargada',
  ],
  '520': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave',
    'Tipo de Pedimento',
    'Fecha de pago',
    'Identificación fiscal del destinatario',
    'Nombre del destinatario de la mercancía',
    'Dirección Destinatario',
  ],
  '551': [
    'Pedimento',
    'Clave de sección aduanera de despacho',
    'Tipo de Operación',
    'Clave de Pedimento',
    'Tipo de Pedimento',
    'Fecha de Pago Real',
    'Fracción arancelaria',
    'Secuencia de la fracción arancelaria',
    'Subdivisión de la fracción arancelaria',
    'Descripción de la mercancía',
    'Precio Unitario MN',
    'Valor Aduana MN Pedimento',
    'Valor Comercial MN Pedimento',
    'Valor en dólares',
    'Cantidad de mercancía en unidades de medida comercial',
    'Clave de unidad de medida comercial',
    'Unidad de medida comercial',
    'Cantidad de mercancía en unidades de medida de la tarifa',
    'Clave de unidad de medida de la tarifa',
    'Unidad de Tarifa',
    'Valor agregado',
    'Clave de vinculación',
    'Clave de método de valorización',
    'Descripción de método de valorización',
    'Código de la mercancía o producto',
    'Marca de la mercancía o producto',
    'Modelo de la mercancía o producto',
    'Clave de país origen / destino',
    'Clave de país Comprador / vendedor',
    'Clave de entidad federativa de origen',
    'Clave de entidad federativa de destino',
    'Clave de entidad federativa del comprador',
    'Clave de entidad federativa del vendedor',
    'Precio Unitario USD',
  ],
  '552': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Fracción Arancelaria', 'Secuencia', 'Kilometraje', 'Fecha Pago',
  ],
  '553': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Fracción Arancelaria', 'Secuencia', 'Clave Permiso',
    'Valor Comercial Dólares', 'Cant. Unidad Tarifa', 'Fecha Pago',
  ],
  '554': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Fracción Arancelaria', 'Secuencia', 'Clave Caso',
    'Identificador Caso', 'Fecha Pago',
  ],
  '556': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Fracción Arancelaria', 'Secuencia', 'Clave Contribución',
    'Tasa Contribución', 'Tipo Tasa', 'Fecha Pago',
  ],
  '557': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Fracción Arancelaria', 'Secuencia', 'Clave Contribución',
    'Forma Pago', 'Importe Pago', 'Fecha Pago',
  ],
  '701': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Patente Rectificada', 'Núm. Ped. Rectificado', 'Sección Rectificada',
    'Clave Documento Rectificado', 'Fecha Pago',
  ],
  '702': [
    'Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera',
    'Clave Contribución', 'Forma Pago Anterior', 'Importe Anterior',
    'Forma Pago Nuevo', 'Importe Nuevo', 'Fecha Pago',
  ],
};

/**
 * Genera encabezados genéricos para archivos sin definición oficial.
 * Siempre incluye "Pedimento" como primer campo.
 */
export const generateFallbackHeaders = (columnCount: number, fileKey: string): string[] => {
  const headers = ['Pedimento', 'Patente', 'Núm. Pedimento', 'Sección Aduanera'];
  for (let i = 4; i < columnCount; i++) {
    headers.push(`Campo ${i - 3}`);
  }
  return headers;
};
